name: CI
on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-11]
        python-version: ["3.8"]


    steps:

    - uses: actions/checkout@v2
    
    - name: Set up Dependencies
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
   
    - name: Setup tea.xyz
    - uses: teaxyz/setup@v0
      with:
        +: |
         +python.org
      
    - name: Initialize 
      run: |
        ockam enroll \
        python3 -m http.server --bind 127.0.0.1 6000 \
        ockam tcp-outlet create --to 6000 \
        ockam relay create        
   
    - name: Setup upterm session
      uses: xgarrido/action-upterm@v1
