name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: xgarrido/action-upterm@v1
